/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CashRegisterRouteImport } from './routes/cash-register'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosSlugRouteImport } from './routes/pos.$slug'
import { Route as CheckoutPlanRouteImport } from './routes/checkout.$plan'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRegisterRoute = CashRegisterRouteImport.update({
  id: '/cash-register',
  path: '/cash-register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosSlugRoute = PosSlugRouteImport.update({
  id: '/pos/$slug',
  path: '/pos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanRoute = CheckoutPlanRouteImport.update({
  id: '/checkout/$plan',
  path: '/checkout/$plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/cash-register': typeof CashRegisterRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/checkout/$plan': typeof CheckoutPlanRoute
  '/pos/$slug': typeof PosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/cash-register': typeof CashRegisterRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/checkout/$plan': typeof CheckoutPlanRoute
  '/pos/$slug': typeof PosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/cash-register': typeof CashRegisterRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/checkout/$plan': typeof CheckoutPlanRoute
  '/pos/$slug': typeof PosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cash-register'
    | '/customers'
    | '/expenses'
    | '/features'
    | '/login'
    | '/pricing'
    | '/products'
    | '/purchases'
    | '/refunds'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/checkout/$plan'
    | '/pos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/cash-register'
    | '/customers'
    | '/expenses'
    | '/features'
    | '/login'
    | '/pricing'
    | '/products'
    | '/purchases'
    | '/refunds'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/checkout/$plan'
    | '/pos/$slug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cash-register'
    | '/customers'
    | '/expenses'
    | '/features'
    | '/login'
    | '/pricing'
    | '/products'
    | '/purchases'
    | '/refunds'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/checkout/$plan'
    | '/pos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CashRegisterRoute: typeof CashRegisterRoute
  CustomersRoute: typeof CustomersRoute
  ExpensesRoute: typeof ExpensesRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  PurchasesRoute: typeof PurchasesRoute
  RefundsRoute: typeof RefundsRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  CheckoutPlanRoute: typeof CheckoutPlanRoute
  PosSlugRoute: typeof PosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-register': {
      id: '/cash-register'
      path: '/cash-register'
      fullPath: '/cash-register'
      preLoaderRoute: typeof CashRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/$slug': {
      id: '/pos/$slug'
      path: '/pos/$slug'
      fullPath: '/pos/$slug'
      preLoaderRoute: typeof PosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$plan': {
      id: '/checkout/$plan'
      path: '/checkout/$plan'
      fullPath: '/checkout/$plan'
      preLoaderRoute: typeof CheckoutPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CashRegisterRoute: CashRegisterRoute,
  CustomersRoute: CustomersRoute,
  ExpensesRoute: ExpensesRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  PurchasesRoute: PurchasesRoute,
  RefundsRoute: RefundsRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  CheckoutPlanRoute: CheckoutPlanRoute,
  PosSlugRoute: PosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
